package com.photogram.grpc.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

public final class ChatOuterClass {
  private ChatOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(ChatOuterClass.Archivo.archivo);
    registry.add(ChatOuterClass.Texto.texto);
  }
  public interface MensajeOrBuilder extends 
      // @@protoc_insertion_point(interface_extends:Mensaje)
       com.google.protobuf.GeneratedMessageLite.
            ExtendableMessageOrBuilder<
                Mensaje, Mensaje.Builder> {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string sender = 2;</code>
     */
    boolean hasSender();
    /**
     * <code>required string sender = 2;</code>
     */
    java.lang.String getSender();
    /**
     * <code>required string sender = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>required string content = 3;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>required string receiver = 4;</code>
     */
    boolean hasReceiver();
    /**
     * <code>required string receiver = 4;</code>
     */
    java.lang.String getReceiver();
    /**
     * <code>required string receiver = 4;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();
  }
  /**
   * Protobuf type {@code Mensaje}
   */
  public  static final class Mensaje extends
      com.google.protobuf.GeneratedMessageLite.ExtendableMessage<
        Mensaje, Mensaje.Builder> implements
      // @@protoc_insertion_point(message_implements:Mensaje)
      MensajeOrBuilder {
    private Mensaje() {
      id_ = "";
      sender_ = "";
      content_ = "";
      receiver_ = "";
    }
    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.String id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      return id_;
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(id_);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    private void setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
    }
    /**
     * <code>optional string id = 1;</code>
     */
    private void clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = getDefaultInstance().getId();
    }
    /**
     * <code>optional string id = 1;</code>
     */
    private void setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value.toStringUtf8();
    }

    public static final int SENDER_FIELD_NUMBER = 2;
    private java.lang.String sender_;
    /**
     * <code>required string sender = 2;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sender = 2;</code>
     */
    public java.lang.String getSender() {
      return sender_;
    }
    /**
     * <code>required string sender = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sender_);
    }
    /**
     * <code>required string sender = 2;</code>
     */
    private void setSender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sender_ = value;
    }
    /**
     * <code>required string sender = 2;</code>
     */
    private void clearSender() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sender_ = getDefaultInstance().getSender();
    }
    /**
     * <code>required string sender = 2;</code>
     */
    private void setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sender_ = value.toStringUtf8();
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.String content_;
    /**
     * <code>required string content = 3;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string content = 3;</code>
     */
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <code>required string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <code>required string content = 3;</code>
     */
    private void setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      content_ = value;
    }
    /**
     * <code>required string content = 3;</code>
     */
    private void clearContent() {
      bitField0_ = (bitField0_ & ~0x00000004);
      content_ = getDefaultInstance().getContent();
    }
    /**
     * <code>required string content = 3;</code>
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      content_ = value.toStringUtf8();
    }

    public static final int RECEIVER_FIELD_NUMBER = 4;
    private java.lang.String receiver_;
    /**
     * <code>required string receiver = 4;</code>
     */
    public boolean hasReceiver() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string receiver = 4;</code>
     */
    public java.lang.String getReceiver() {
      return receiver_;
    }
    /**
     * <code>required string receiver = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(receiver_);
    }
    /**
     * <code>required string receiver = 4;</code>
     */
    private void setReceiver(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      receiver_ = value;
    }
    /**
     * <code>required string receiver = 4;</code>
     */
    private void clearReceiver() {
      bitField0_ = (bitField0_ & ~0x00000008);
      receiver_ = getDefaultInstance().getReceiver();
    }
    /**
     * <code>required string receiver = 4;</code>
     */
    private void setReceiverBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      receiver_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageLite
        .ExtendableMessage<ChatOuterClass.Mensaje, ChatOuterClass.Mensaje.Builder>
          .ExtensionWriter extensionWriter =
            newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getId());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getSender());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getContent());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeString(4, getReceiver());
      }
      extensionWriter.writeUntil(79, output);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getId());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getSender());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getContent());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getReceiver());
      }
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static ChatOuterClass.Mensaje parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ChatOuterClass.Mensaje parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ChatOuterClass.Mensaje parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ChatOuterClass.Mensaje parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ChatOuterClass.Mensaje parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Mensaje parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ChatOuterClass.Mensaje parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Mensaje parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ChatOuterClass.Mensaje parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Mensaje parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatOuterClass.Mensaje prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Mensaje}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.ExtendableBuilder<
          ChatOuterClass.Mensaje, Builder> implements
        // @@protoc_insertion_point(builder_implements:Mensaje)
        ChatOuterClass.MensajeOrBuilder {
      // Construct using com.photogram.grpc.grpc.ChatOuterClass.Mensaje.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return instance.hasId();
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        return instance.getId();
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        return instance.getIdBytes();
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdBytes(value);
        return this;
      }

      /**
       * <code>required string sender = 2;</code>
       */
      public boolean hasSender() {
        return instance.hasSender();
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public java.lang.String getSender() {
        return instance.getSender();
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        return instance.getSenderBytes();
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        copyOnWrite();
        instance.setSender(value);
        return this;
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public Builder clearSender() {
        copyOnWrite();
        instance.clearSender();
        return this;
      }
      /**
       * <code>required string sender = 2;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSenderBytes(value);
        return this;
      }

      /**
       * <code>required string content = 3;</code>
       */
      public boolean hasContent() {
        return instance.hasContent();
      }
      /**
       * <code>required string content = 3;</code>
       */
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <code>required string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <code>required string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      /**
       * <code>required string receiver = 4;</code>
       */
      public boolean hasReceiver() {
        return instance.hasReceiver();
      }
      /**
       * <code>required string receiver = 4;</code>
       */
      public java.lang.String getReceiver() {
        return instance.getReceiver();
      }
      /**
       * <code>required string receiver = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        return instance.getReceiverBytes();
      }
      /**
       * <code>required string receiver = 4;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        copyOnWrite();
        instance.setReceiver(value);
        return this;
      }
      /**
       * <code>required string receiver = 4;</code>
       */
      public Builder clearReceiver() {
        copyOnWrite();
        instance.clearReceiver();
        return this;
      }
      /**
       * <code>required string receiver = 4;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setReceiverBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Mensaje)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ChatOuterClass.Mensaje();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasSender()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasContent()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasReceiver()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!extensionsAreInitialized()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ChatOuterClass.Mensaje other = (ChatOuterClass.Mensaje) arg1;
          id_ = visitor.visitString(
              hasId(), id_,
              other.hasId(), other.id_);
          sender_ = visitor.visitString(
              hasSender(), sender_,
              other.hasSender(), other.sender_);
          content_ = visitor.visitString(
              hasContent(), content_,
              other.hasContent(), other.content_);
          receiver_ = visitor.visitString(
              hasReceiver(), receiver_,
              other.hasReceiver(), other.receiver_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(getDefaultInstanceForType(),
                                         input, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  id_ = s;
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  sender_ = s;
                  break;
                }
                case 26: {
                  String s = input.readString();
                  bitField0_ |= 0x00000004;
                  content_ = s;
                  break;
                }
                case 34: {
                  String s = input.readString();
                  bitField0_ |= 0x00000008;
                  receiver_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ChatOuterClass.Mensaje.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Mensaje)
    private static final ChatOuterClass.Mensaje DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Mensaje();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ChatOuterClass.Mensaje getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Mensaje> PARSER;

    public static com.google.protobuf.Parser<Mensaje> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ArchivoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Archivo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bytes contenido = 1;</code>
     */
    boolean hasContenido();
    /**
     * <code>optional bytes contenido = 1;</code>
     */
    com.google.protobuf.ByteString getContenido();

    /**
     * <code>optional string ruta = 2;</code>
     */
    boolean hasRuta();
    /**
     * <code>optional string ruta = 2;</code>
     */
    java.lang.String getRuta();
    /**
     * <code>optional string ruta = 2;</code>
     */
    com.google.protobuf.ByteString
        getRutaBytes();
  }
  /**
   * Protobuf type {@code Archivo}
   */
  public  static final class Archivo extends
      com.google.protobuf.GeneratedMessageLite<
          Archivo, Archivo.Builder> implements
      // @@protoc_insertion_point(message_implements:Archivo)
      ArchivoOrBuilder {
    private Archivo() {
      contenido_ = com.google.protobuf.ByteString.EMPTY;
      ruta_ = "";
    }
    private int bitField0_;
    public static final int CONTENIDO_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString contenido_;
    /**
     * <code>optional bytes contenido = 1;</code>
     */
    public boolean hasContenido() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes contenido = 1;</code>
     */
    public com.google.protobuf.ByteString getContenido() {
      return contenido_;
    }
    /**
     * <code>optional bytes contenido = 1;</code>
     */
    private void setContenido(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      contenido_ = value;
    }
    /**
     * <code>optional bytes contenido = 1;</code>
     */
    private void clearContenido() {
      bitField0_ = (bitField0_ & ~0x00000001);
      contenido_ = getDefaultInstance().getContenido();
    }

    public static final int RUTA_FIELD_NUMBER = 2;
    private java.lang.String ruta_;
    /**
     * <code>optional string ruta = 2;</code>
     */
    public boolean hasRuta() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string ruta = 2;</code>
     */
    public java.lang.String getRuta() {
      return ruta_;
    }
    /**
     * <code>optional string ruta = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRutaBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ruta_);
    }
    /**
     * <code>optional string ruta = 2;</code>
     */
    private void setRuta(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      ruta_ = value;
    }
    /**
     * <code>optional string ruta = 2;</code>
     */
    private void clearRuta() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ruta_ = getDefaultInstance().getRuta();
    }
    /**
     * <code>optional string ruta = 2;</code>
     */
    private void setRutaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      ruta_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, contenido_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getRuta());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, contenido_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getRuta());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static ChatOuterClass.Archivo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ChatOuterClass.Archivo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ChatOuterClass.Archivo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ChatOuterClass.Archivo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ChatOuterClass.Archivo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Archivo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ChatOuterClass.Archivo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Archivo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ChatOuterClass.Archivo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Archivo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatOuterClass.Archivo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Archivo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ChatOuterClass.Archivo, Builder> implements
        // @@protoc_insertion_point(builder_implements:Archivo)
        ChatOuterClass.ArchivoOrBuilder {
      // Construct using com.photogram.grpc.grpc.ChatOuterClass.Archivo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional bytes contenido = 1;</code>
       */
      public boolean hasContenido() {
        return instance.hasContenido();
      }
      /**
       * <code>optional bytes contenido = 1;</code>
       */
      public com.google.protobuf.ByteString getContenido() {
        return instance.getContenido();
      }
      /**
       * <code>optional bytes contenido = 1;</code>
       */
      public Builder setContenido(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContenido(value);
        return this;
      }
      /**
       * <code>optional bytes contenido = 1;</code>
       */
      public Builder clearContenido() {
        copyOnWrite();
        instance.clearContenido();
        return this;
      }

      /**
       * <code>optional string ruta = 2;</code>
       */
      public boolean hasRuta() {
        return instance.hasRuta();
      }
      /**
       * <code>optional string ruta = 2;</code>
       */
      public java.lang.String getRuta() {
        return instance.getRuta();
      }
      /**
       * <code>optional string ruta = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRutaBytes() {
        return instance.getRutaBytes();
      }
      /**
       * <code>optional string ruta = 2;</code>
       */
      public Builder setRuta(
          java.lang.String value) {
        copyOnWrite();
        instance.setRuta(value);
        return this;
      }
      /**
       * <code>optional string ruta = 2;</code>
       */
      public Builder clearRuta() {
        copyOnWrite();
        instance.clearRuta();
        return this;
      }
      /**
       * <code>optional string ruta = 2;</code>
       */
      public Builder setRutaBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRutaBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Archivo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ChatOuterClass.Archivo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ChatOuterClass.Archivo other = (ChatOuterClass.Archivo) arg1;
          contenido_ = visitor.visitByteString(
              hasContenido(), contenido_,
              other.hasContenido(), other.contenido_);
          ruta_ = visitor.visitString(
              hasRuta(), ruta_,
              other.hasRuta(), other.ruta_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  bitField0_ |= 0x00000001;
                  contenido_ = input.readBytes();
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  ruta_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ChatOuterClass.Archivo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Archivo)
    private static final ChatOuterClass.Archivo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Archivo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ChatOuterClass.Archivo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Archivo> PARSER;

    public static com.google.protobuf.Parser<Archivo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int ARCHIVO_FIELD_NUMBER = 77;
    /**
     * <code>extend .Mensaje { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        ChatOuterClass.Mensaje,
        ChatOuterClass.Archivo> archivo = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          ChatOuterClass.Mensaje.getDefaultInstance(),
          ChatOuterClass.Archivo.getDefaultInstance(),
          ChatOuterClass.Archivo.getDefaultInstance(),
          null,
          77,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          ChatOuterClass.Archivo.class);
  }

  public interface TextoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Texto)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string contenido = 1;</code>
     */
    boolean hasContenido();
    /**
     * <code>required string contenido = 1;</code>
     */
    java.lang.String getContenido();
    /**
     * <code>required string contenido = 1;</code>
     */
    com.google.protobuf.ByteString
        getContenidoBytes();

    /**
     * <code>required bool editado = 2;</code>
     */
    boolean hasEditado();
    /**
     * <code>required bool editado = 2;</code>
     */
    boolean getEditado();
  }
  /**
   * Protobuf type {@code Texto}
   */
  public  static final class Texto extends
      com.google.protobuf.GeneratedMessageLite<
          Texto, Texto.Builder> implements
      // @@protoc_insertion_point(message_implements:Texto)
      TextoOrBuilder {
    private Texto() {
      contenido_ = "";
    }
    private int bitField0_;
    public static final int CONTENIDO_FIELD_NUMBER = 1;
    private java.lang.String contenido_;
    /**
     * <code>required string contenido = 1;</code>
     */
    public boolean hasContenido() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string contenido = 1;</code>
     */
    public java.lang.String getContenido() {
      return contenido_;
    }
    /**
     * <code>required string contenido = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContenidoBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(contenido_);
    }
    /**
     * <code>required string contenido = 1;</code>
     */
    private void setContenido(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      contenido_ = value;
    }
    /**
     * <code>required string contenido = 1;</code>
     */
    private void clearContenido() {
      bitField0_ = (bitField0_ & ~0x00000001);
      contenido_ = getDefaultInstance().getContenido();
    }
    /**
     * <code>required string contenido = 1;</code>
     */
    private void setContenidoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      contenido_ = value.toStringUtf8();
    }

    public static final int EDITADO_FIELD_NUMBER = 2;
    private boolean editado_;
    /**
     * <code>required bool editado = 2;</code>
     */
    public boolean hasEditado() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool editado = 2;</code>
     */
    public boolean getEditado() {
      return editado_;
    }
    /**
     * <code>required bool editado = 2;</code>
     */
    private void setEditado(boolean value) {
      bitField0_ |= 0x00000002;
      editado_ = value;
    }
    /**
     * <code>required bool editado = 2;</code>
     */
    private void clearEditado() {
      bitField0_ = (bitField0_ & ~0x00000002);
      editado_ = false;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getContenido());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, editado_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getContenido());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, editado_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static ChatOuterClass.Texto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ChatOuterClass.Texto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ChatOuterClass.Texto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ChatOuterClass.Texto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ChatOuterClass.Texto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Texto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ChatOuterClass.Texto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Texto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ChatOuterClass.Texto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Texto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatOuterClass.Texto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Texto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ChatOuterClass.Texto, Builder> implements
        // @@protoc_insertion_point(builder_implements:Texto)
        ChatOuterClass.TextoOrBuilder {
      // Construct using com.photogram.grpc.grpc.ChatOuterClass.Texto.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string contenido = 1;</code>
       */
      public boolean hasContenido() {
        return instance.hasContenido();
      }
      /**
       * <code>required string contenido = 1;</code>
       */
      public java.lang.String getContenido() {
        return instance.getContenido();
      }
      /**
       * <code>required string contenido = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContenidoBytes() {
        return instance.getContenidoBytes();
      }
      /**
       * <code>required string contenido = 1;</code>
       */
      public Builder setContenido(
          java.lang.String value) {
        copyOnWrite();
        instance.setContenido(value);
        return this;
      }
      /**
       * <code>required string contenido = 1;</code>
       */
      public Builder clearContenido() {
        copyOnWrite();
        instance.clearContenido();
        return this;
      }
      /**
       * <code>required string contenido = 1;</code>
       */
      public Builder setContenidoBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContenidoBytes(value);
        return this;
      }

      /**
       * <code>required bool editado = 2;</code>
       */
      public boolean hasEditado() {
        return instance.hasEditado();
      }
      /**
       * <code>required bool editado = 2;</code>
       */
      public boolean getEditado() {
        return instance.getEditado();
      }
      /**
       * <code>required bool editado = 2;</code>
       */
      public Builder setEditado(boolean value) {
        copyOnWrite();
        instance.setEditado(value);
        return this;
      }
      /**
       * <code>required bool editado = 2;</code>
       */
      public Builder clearEditado() {
        copyOnWrite();
        instance.clearEditado();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Texto)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ChatOuterClass.Texto();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasContenido()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasEditado()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ChatOuterClass.Texto other = (ChatOuterClass.Texto) arg1;
          contenido_ = visitor.visitString(
              hasContenido(), contenido_,
              other.hasContenido(), other.contenido_);
          editado_ = visitor.visitBoolean(
              hasEditado(), editado_,
              other.hasEditado(), other.editado_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  contenido_ = s;
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  editado_ = input.readBool();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ChatOuterClass.Texto.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Texto)
    private static final ChatOuterClass.Texto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Texto();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ChatOuterClass.Texto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Texto> PARSER;

    public static com.google.protobuf.Parser<Texto> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int TEXTO_FIELD_NUMBER = 78;
    /**
     * <code>extend .Mensaje { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        ChatOuterClass.Mensaje,
        ChatOuterClass.Texto> texto = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          ChatOuterClass.Mensaje.getDefaultInstance(),
          ChatOuterClass.Texto.getDefaultInstance(),
          ChatOuterClass.Texto.getDefaultInstance(),
          null,
          78,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          ChatOuterClass.Texto.class);
  }

  public interface UsuarioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Usuario)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string username = 1;</code>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 1;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>required string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();
  }
  /**
   * Protobuf type {@code Usuario}
   */
  public  static final class Usuario extends
      com.google.protobuf.GeneratedMessageLite<
          Usuario, Usuario.Builder> implements
      // @@protoc_insertion_point(message_implements:Usuario)
      UsuarioOrBuilder {
    private Usuario() {
      username_ = "";
    }
    private int bitField0_;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.String username_;
    /**
     * <code>required string username = 1;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string username = 1;</code>
     */
    public java.lang.String getUsername() {
      return username_;
    }
    /**
     * <code>required string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(username_);
    }
    /**
     * <code>required string username = 1;</code>
     */
    private void setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      username_ = value;
    }
    /**
     * <code>required string username = 1;</code>
     */
    private void clearUsername() {
      bitField0_ = (bitField0_ & ~0x00000001);
      username_ = getDefaultInstance().getUsername();
    }
    /**
     * <code>required string username = 1;</code>
     */
    private void setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      username_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getUsername());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUsername());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static ChatOuterClass.Usuario parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ChatOuterClass.Usuario parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ChatOuterClass.Usuario parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ChatOuterClass.Usuario parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ChatOuterClass.Usuario parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Usuario parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ChatOuterClass.Usuario parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Usuario parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ChatOuterClass.Usuario parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Usuario parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatOuterClass.Usuario prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Usuario}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ChatOuterClass.Usuario, Builder> implements
        // @@protoc_insertion_point(builder_implements:Usuario)
        ChatOuterClass.UsuarioOrBuilder {
      // Construct using com.photogram.grpc.grpc.ChatOuterClass.Usuario.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string username = 1;</code>
       */
      public boolean hasUsername() {
        return instance.hasUsername();
      }
      /**
       * <code>required string username = 1;</code>
       */
      public java.lang.String getUsername() {
        return instance.getUsername();
      }
      /**
       * <code>required string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        return instance.getUsernameBytes();
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        copyOnWrite();
        instance.setUsername(value);
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder clearUsername() {
        copyOnWrite();
        instance.clearUsername();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUsernameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Usuario)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ChatOuterClass.Usuario();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasUsername()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ChatOuterClass.Usuario other = (ChatOuterClass.Usuario) arg1;
          username_ = visitor.visitString(
              hasUsername(), username_,
              other.hasUsername(), other.username_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  username_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ChatOuterClass.Usuario.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Usuario)
    private static final ChatOuterClass.Usuario DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Usuario();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ChatOuterClass.Usuario getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Usuario> PARSER;

    public static com.google.protobuf.Parser<Usuario> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>required string response = 1;</code>
     */
    java.lang.String getResponse();
    /**
     * <code>required string response = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseBytes();
  }
  /**
   * Protobuf type {@code Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageLite<
          Empty, Empty.Builder> implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
    private Empty() {
      response_ = "";
    }
    private int bitField0_;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private java.lang.String response_;
    /**
     * <code>required string response = 1;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string response = 1;</code>
     */
    public java.lang.String getResponse() {
      return response_;
    }
    /**
     * <code>required string response = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(response_);
    }
    /**
     * <code>required string response = 1;</code>
     */
    private void setResponse(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      response_ = value;
    }
    /**
     * <code>required string response = 1;</code>
     */
    private void clearResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      response_ = getDefaultInstance().getResponse();
    }
    /**
     * <code>required string response = 1;</code>
     */
    private void setResponseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      response_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getResponse());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getResponse());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static ChatOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ChatOuterClass.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ChatOuterClass.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ChatOuterClass.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ChatOuterClass.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ChatOuterClass.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ChatOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ChatOuterClass.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatOuterClass.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ChatOuterClass.Empty, Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        ChatOuterClass.EmptyOrBuilder {
      // Construct using com.photogram.grpc.grpc.ChatOuterClass.Empty.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string response = 1;</code>
       */
      public boolean hasResponse() {
        return instance.hasResponse();
      }
      /**
       * <code>required string response = 1;</code>
       */
      public java.lang.String getResponse() {
        return instance.getResponse();
      }
      /**
       * <code>required string response = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        return instance.getResponseBytes();
      }
      /**
       * <code>required string response = 1;</code>
       */
      public Builder setResponse(
          java.lang.String value) {
        copyOnWrite();
        instance.setResponse(value);
        return this;
      }
      /**
       * <code>required string response = 1;</code>
       */
      public Builder clearResponse() {
        copyOnWrite();
        instance.clearResponse();
        return this;
      }
      /**
       * <code>required string response = 1;</code>
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setResponseBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Empty)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ChatOuterClass.Empty();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasResponse()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ChatOuterClass.Empty other = (ChatOuterClass.Empty) arg1;
          response_ = visitor.visitString(
              hasResponse(), response_,
              other.hasResponse(), other.response_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  response_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ChatOuterClass.Empty.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Empty)
    private static final ChatOuterClass.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Empty();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ChatOuterClass.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Empty> PARSER;

    public static com.google.protobuf.Parser<Empty> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
